//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_Employees_ProductsView
    {
        public int ID { get; set; }
        public string Фамилия_сотрудника { get; set; }
        public string Имя_сотрудника { get; set; }
        public string Отчество_сотрудника { get; set; }
        public int Возраст_сотрудника { get; set; }
        public string Название_товара { get; set; }
        public int Цена_товара_в_рублях { get; set; }
    }
}
